#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VantecDemoQ1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertorders(orders instance);
    partial void Updateorders(orders instance);
    partial void Deleteorders(orders instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<orders> orders
		{
			get
			{
				return this.GetTable<orders>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orders")]
	public partial class orders : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _fromadds;
		
		private string _frompostcode;
		
		private string _toadds;
		
		private string _topostcode;
		
		private string _packagetype;
		
		private int _packageamount;
		
		private int _price;
		
		private System.Nullable<int> _width;
		
		private System.Nullable<int> _height;
		
		private System.Nullable<int> _length;
		
		private System.Nullable<int> _weight;
		
		private string _goodskind;
		
		private System.Nullable<System.DateTime> _clientstartdate;
		
		private System.Nullable<System.DateTime> _clientenddate;
		
		private string _packagedep;
		
		private string _clientnote;
		
		private string _sender;
		
		private string _driver;
		
		private string _trucknumber;
		
		private string _trucktype;
		
		private string _driverphonenumber;
		
		private System.Nullable<System.DateTime> _pickupdate;
		
		private System.Nullable<System.DateTime> _dropoffdate;
		
		private string _note;
		
		private System.Nullable<System.DateTime> _modifydate;
		
		private System.Nullable<System.DateTime> _createdate;
		
		private string _state;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnfromaddsChanging(string value);
    partial void OnfromaddsChanged();
    partial void OnfrompostcodeChanging(string value);
    partial void OnfrompostcodeChanged();
    partial void OntoaddsChanging(string value);
    partial void OntoaddsChanged();
    partial void OntopostcodeChanging(string value);
    partial void OntopostcodeChanged();
    partial void OnpackagetypeChanging(string value);
    partial void OnpackagetypeChanged();
    partial void OnpackageamountChanging(int value);
    partial void OnpackageamountChanged();
    partial void OnpriceChanging(int value);
    partial void OnpriceChanged();
    partial void OnwidthChanging(System.Nullable<int> value);
    partial void OnwidthChanged();
    partial void OnheightChanging(System.Nullable<int> value);
    partial void OnheightChanged();
    partial void OnlengthChanging(System.Nullable<int> value);
    partial void OnlengthChanged();
    partial void OnweightChanging(System.Nullable<int> value);
    partial void OnweightChanged();
    partial void OngoodskindChanging(string value);
    partial void OngoodskindChanged();
    partial void OnclientstartdateChanging(System.Nullable<System.DateTime> value);
    partial void OnclientstartdateChanged();
    partial void OnclientenddateChanging(System.Nullable<System.DateTime> value);
    partial void OnclientenddateChanged();
    partial void OnpackagedepChanging(string value);
    partial void OnpackagedepChanged();
    partial void OnclientnoteChanging(string value);
    partial void OnclientnoteChanged();
    partial void OnsenderChanging(string value);
    partial void OnsenderChanged();
    partial void OndriverChanging(string value);
    partial void OndriverChanged();
    partial void OntrucknumberChanging(string value);
    partial void OntrucknumberChanged();
    partial void OntrucktypeChanging(string value);
    partial void OntrucktypeChanged();
    partial void OndriverphonenumberChanging(string value);
    partial void OndriverphonenumberChanged();
    partial void OnpickupdateChanging(System.Nullable<System.DateTime> value);
    partial void OnpickupdateChanged();
    partial void OndropoffdateChanging(System.Nullable<System.DateTime> value);
    partial void OndropoffdateChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OnmodifydateChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifydateChanged();
    partial void OncreatedateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedateChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    #endregion
		
		public orders()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fromadds", DbType="NVarChar(MAX)")]
		public string fromadds
		{
			get
			{
				return this._fromadds;
			}
			set
			{
				if ((this._fromadds != value))
				{
					this.OnfromaddsChanging(value);
					this.SendPropertyChanging();
					this._fromadds = value;
					this.SendPropertyChanged("fromadds");
					this.OnfromaddsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frompostcode", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string frompostcode
		{
			get
			{
				return this._frompostcode;
			}
			set
			{
				if ((this._frompostcode != value))
				{
					this.OnfrompostcodeChanging(value);
					this.SendPropertyChanging();
					this._frompostcode = value;
					this.SendPropertyChanged("frompostcode");
					this.OnfrompostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_toadds", DbType="NVarChar(MAX)")]
		public string toadds
		{
			get
			{
				return this._toadds;
			}
			set
			{
				if ((this._toadds != value))
				{
					this.OntoaddsChanging(value);
					this.SendPropertyChanging();
					this._toadds = value;
					this.SendPropertyChanged("toadds");
					this.OntoaddsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topostcode", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string topostcode
		{
			get
			{
				return this._topostcode;
			}
			set
			{
				if ((this._topostcode != value))
				{
					this.OntopostcodeChanging(value);
					this.SendPropertyChanging();
					this._topostcode = value;
					this.SendPropertyChanged("topostcode");
					this.OntopostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_packagetype", DbType="NChar(10)")]
		public string packagetype
		{
			get
			{
				return this._packagetype;
			}
			set
			{
				if ((this._packagetype != value))
				{
					this.OnpackagetypeChanging(value);
					this.SendPropertyChanging();
					this._packagetype = value;
					this.SendPropertyChanged("packagetype");
					this.OnpackagetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_packageamount", DbType="Int NOT NULL")]
		public int packageamount
		{
			get
			{
				return this._packageamount;
			}
			set
			{
				if ((this._packageamount != value))
				{
					this.OnpackageamountChanging(value);
					this.SendPropertyChanging();
					this._packageamount = value;
					this.SendPropertyChanged("packageamount");
					this.OnpackageamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int NOT NULL")]
		public int price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_width", DbType="Int")]
		public System.Nullable<int> width
		{
			get
			{
				return this._width;
			}
			set
			{
				if ((this._width != value))
				{
					this.OnwidthChanging(value);
					this.SendPropertyChanging();
					this._width = value;
					this.SendPropertyChanged("width");
					this.OnwidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="Int")]
		public System.Nullable<int> height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this.OnheightChanging(value);
					this.SendPropertyChanging();
					this._height = value;
					this.SendPropertyChanged("height");
					this.OnheightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_length", DbType="Int")]
		public System.Nullable<int> length
		{
			get
			{
				return this._length;
			}
			set
			{
				if ((this._length != value))
				{
					this.OnlengthChanging(value);
					this.SendPropertyChanging();
					this._length = value;
					this.SendPropertyChanged("length");
					this.OnlengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="Int")]
		public System.Nullable<int> weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				if ((this._weight != value))
				{
					this.OnweightChanging(value);
					this.SendPropertyChanging();
					this._weight = value;
					this.SendPropertyChanged("weight");
					this.OnweightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_goodskind", DbType="NVarChar(MAX)")]
		public string goodskind
		{
			get
			{
				return this._goodskind;
			}
			set
			{
				if ((this._goodskind != value))
				{
					this.OngoodskindChanging(value);
					this.SendPropertyChanging();
					this._goodskind = value;
					this.SendPropertyChanged("goodskind");
					this.OngoodskindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientstartdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> clientstartdate
		{
			get
			{
				return this._clientstartdate;
			}
			set
			{
				if ((this._clientstartdate != value))
				{
					this.OnclientstartdateChanging(value);
					this.SendPropertyChanging();
					this._clientstartdate = value;
					this.SendPropertyChanged("clientstartdate");
					this.OnclientstartdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientenddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> clientenddate
		{
			get
			{
				return this._clientenddate;
			}
			set
			{
				if ((this._clientenddate != value))
				{
					this.OnclientenddateChanging(value);
					this.SendPropertyChanging();
					this._clientenddate = value;
					this.SendPropertyChanged("clientenddate");
					this.OnclientenddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_packagedep", DbType="NChar(10)")]
		public string packagedep
		{
			get
			{
				return this._packagedep;
			}
			set
			{
				if ((this._packagedep != value))
				{
					this.OnpackagedepChanging(value);
					this.SendPropertyChanging();
					this._packagedep = value;
					this.SendPropertyChanged("packagedep");
					this.OnpackagedepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientnote", DbType="NVarChar(MAX)")]
		public string clientnote
		{
			get
			{
				return this._clientnote;
			}
			set
			{
				if ((this._clientnote != value))
				{
					this.OnclientnoteChanging(value);
					this.SendPropertyChanging();
					this._clientnote = value;
					this.SendPropertyChanged("clientnote");
					this.OnclientnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sender", DbType="NChar(10)")]
		public string sender
		{
			get
			{
				return this._sender;
			}
			set
			{
				if ((this._sender != value))
				{
					this.OnsenderChanging(value);
					this.SendPropertyChanging();
					this._sender = value;
					this.SendPropertyChanged("sender");
					this.OnsenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driver", DbType="NChar(10)")]
		public string driver
		{
			get
			{
				return this._driver;
			}
			set
			{
				if ((this._driver != value))
				{
					this.OndriverChanging(value);
					this.SendPropertyChanging();
					this._driver = value;
					this.SendPropertyChanged("driver");
					this.OndriverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trucknumber", DbType="NChar(10)")]
		public string trucknumber
		{
			get
			{
				return this._trucknumber;
			}
			set
			{
				if ((this._trucknumber != value))
				{
					this.OntrucknumberChanging(value);
					this.SendPropertyChanging();
					this._trucknumber = value;
					this.SendPropertyChanged("trucknumber");
					this.OntrucknumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trucktype", DbType="NChar(10)")]
		public string trucktype
		{
			get
			{
				return this._trucktype;
			}
			set
			{
				if ((this._trucktype != value))
				{
					this.OntrucktypeChanging(value);
					this.SendPropertyChanging();
					this._trucktype = value;
					this.SendPropertyChanged("trucktype");
					this.OntrucktypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driverphonenumber", DbType="NChar(50)")]
		public string driverphonenumber
		{
			get
			{
				return this._driverphonenumber;
			}
			set
			{
				if ((this._driverphonenumber != value))
				{
					this.OndriverphonenumberChanging(value);
					this.SendPropertyChanging();
					this._driverphonenumber = value;
					this.SendPropertyChanged("driverphonenumber");
					this.OndriverphonenumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pickupdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> pickupdate
		{
			get
			{
				return this._pickupdate;
			}
			set
			{
				if ((this._pickupdate != value))
				{
					this.OnpickupdateChanging(value);
					this.SendPropertyChanging();
					this._pickupdate = value;
					this.SendPropertyChanged("pickupdate");
					this.OnpickupdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dropoffdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dropoffdate
		{
			get
			{
				return this._dropoffdate;
			}
			set
			{
				if ((this._dropoffdate != value))
				{
					this.OndropoffdateChanging(value);
					this.SendPropertyChanging();
					this._dropoffdate = value;
					this.SendPropertyChanged("dropoffdate");
					this.OndropoffdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(MAX)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifydate", DbType="DateTime")]
		public System.Nullable<System.DateTime> modifydate
		{
			get
			{
				return this._modifydate;
			}
			set
			{
				if ((this._modifydate != value))
				{
					this.OnmodifydateChanging(value);
					this.SendPropertyChanging();
					this._modifydate = value;
					this.SendPropertyChanged("modifydate");
					this.OnmodifydateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				if ((this._createdate != value))
				{
					this.OncreatedateChanging(value);
					this.SendPropertyChanging();
					this._createdate = value;
					this.SendPropertyChanged("createdate");
					this.OncreatedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", CanBeNull=false)]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
